#!/usr/bin/env python3
# pylint: disable=C0116,W0613

import os,sys
import subprocess

def gitleaksInstalled():
    try:
        subprocess.call(["gitleaks", "version"])
        return True
    except FileNotFoundError:
        return False

if gitleaksInstalled():
    exitCode = os.WEXITSTATUS(os.system("gitleaks protect -v --staged -c gitleaks.toml"))
    if exitCode == 1:
        print("Warning! gitleaks has detected sensitive information in your changes.")
        sys.exit(1)
else:
    print("gitleaks is not installed or in the PATH.")
    sys.exit(1)
